// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfqqkvhzqtdxzofkwyyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcXFrdmh6cXRkeHpvZmt3eXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDA1MjgsImV4cCI6MjA1ODY3NjUyOH0.PXijWD98Jds-RoWkZvHvt6CPI2aogcm4cIhvF9ApvRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);